<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->htmlStartForm('edit') ?>
<table class="great_table sectionEdit cmfHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
</tr>
<tr>
<td class="svet_td">Новостей на главной</td>
<td class="svet_td2"><?=$configForm->html('newsMain', 'class="width25"') ?></td>
</tr>
<tr>
<td class="svet_td">Новостей на страницу</td>
<td class="svet_td2"><?=$configForm->html('newsLimit', 'class="width25"') ?></td>
</tr>
<tr>
<td class="svet_td">Количество страниц (навигация)</td>
<td class="svet_td2"><?=$configForm->html('newsPage', 'class="width25"') ?></td>
</tr>
</table>
<?=$config->htmlEndForm() ?>

	<? view_command::viewLimitButton($main_list->getLimitUrl(), $main_list->getLinkPage(),
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="50px">Дата</td>
	<td width="20%">Заголовок</td>
	<td>Анонс</td>
	<td width="200px">Постоянная ссылка</td>
	<td width="22px">Вверху списка</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($main_list) ?>
	<td><?=$data->date ?></td>
	<td><? if($key) echo cmfAdminView::buttonType3($main_list->getEditUrl(), $data->header) ?></td>
	<td><?=$data->notice ?></td>
	<td><?=$main_list->viewListSiteUrl($data) ?></td>
	<td><?=$form->html('isMain') ?></td>
	<td><?=$form->html('visible') ?></td>
	<td><?=$main_list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLimitButton($main_list->getLimitUrl(), $main_list->getLinkPage(),
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
