	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("edit.postAjax('update');", 'Применить')) ?>


<?=$main_edit->htmlStartForm('edit') ?>
<table class="great_table">
<tr class="header_col">
<td colspan="2">Настройки для прайса <?=view_siteUrl::viewSiteUrl(cmfCronSiteMap::getUrlFile()) ?></td>
</tr>

</table>
<?=$main_edit->htmlEndForm() ?>

	<? view_command::viewLineMenuButton(
	                   cmfAdminView::buttonType1("edit.postAjax('updateSitemap');", 'Сгенерировать файл'),
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить').
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table width="1000px" class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td>Модуль</td>
	<td width="150px">Вероятная частота изменения</td>
	<td width="100px">Приоритетность</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	$i = false;
	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($main_list) ?>
	<?=$main_list->getPostMove($data); ?>

	<td><?=$form->html('name', 'class="width50"') ?></td>
	<td><?=$form->html('changefreq', 'class="width99"') ?></td>
	<td><?=$form->html('priority', 'class="width50"') ?></td>
	<td><?=$form->html('visible') ?></td>
    <td><?=$main_list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить').
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>