	<table class="table_position">
	<tr class="header_col">
	<td>Группы: <?=cmfView::selectOncahge($filterGroup) ?></td>
	</tr>
	</table>

	<? view_command::viewLimitButton($limitUrl, $linkPage,
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="100px">Имя</td>
	<td width="700px">Логин</td>
	<td width="22px">debugError</td>
	<td width="22px">debugSql</td>
	<td width="22px">debugExplain</td>
	<td width="22px">debugCache</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($main_list) ?>

	<td><?=$data->name ?></td>
	<td><?=$data->login ?></td>


	<td><?=$form->html('debugError') ?></td>
	<td><?=$form->html('debugSql') ?></td>
	<td><?=$form->html('debugExplain') ?></td>
	<td><?=$form->html('debugCache') ?>
		<?=$main_list->viewListId(); ?>
	</td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLimitButton($limitUrl, $linkPage,
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
