	<? view_command::viewLimitButton($limitUrl, $linkPage,
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td>Название</td>
	<td width="22px">Главная</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($main_list) ?>
	<?=$main_list->getPostMove($data) ?>
	<td><? if($key) echo cmfAdminView::buttonType3($main_list->getEditUrl(), $data->name) ?></td>
	<td><?=$form->html('main') ?></td>
	<td><?=$form->html('visible') ?></td>
    <td><?=$main_list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLimitButton($limitUrl, $linkPage,
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
