	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("edit.postAjax('update');", 'Применить')) ?>


<?=$main_edit->htmlStartForm('edit') ?>
<table class="great_table">
<tr class="header_col">
<td colspan="2">Настройки</td>
</tr>

</table>
<?=$main_edit->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить').
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table width="1000px" class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td>Модуль</td>
	<td width="150px">Обновлять</td>
	<td width="150px">Статус</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	$i = false;
	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($main_list) ?>
	<?=$main_list->getPostMove($data); ?>

	<td><?=$form->html('name', 'style="width:75%"') ?></td>
	<td><?=$form->html('changefreq', 'class="width99"') ?></td>
	<td nowrap><? if($data->status=='start' or $data->status=='end') { ?>
			<?=$data->status=='start' ? 'Старт': 'Выполнен' ?><br /><?=$data->date ?>
		<? } ?>
	</td>
	<td><?=$form->html('visible') ?></td>
    <td><?=$main_list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить').
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>