
<table class="great_table">
<tr class="header_col">
<td colspan="2"><?=$url ?></td>
</tr>
</table>

	<? view_command::viewLineMenuButton(
	                   cmfAdminView::buttonType1("window.open('". $main_edit->getSelectUrl() ."', 'param').focus();;", 'Открыть фильтры товара') .
                       cmfAdminView::buttonType1("window.open('". $main_edit->getNoticeUrl() ."', 'param').focus();", 'Открыть параметры описание товара'),
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>

<?=$main_edit->htmlStartForm() ?>
<table class="great_table">
<tr class="header_col">
<td colspan="4">Параметры</td>
</tr>
<?=$main_edit->paramView() ?>
</table>
<?=$main_edit->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>