	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="25px">&nbsp;</td>
	<td>Скидка %</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($main_list) ?>

	<td><? if($data->is('image')) { ?>
	    <img src="<?=cmfPathDiscount ?><?=$data->image ?>" height="20px">
	<? } ?></td>
	<td><?=cmfAdminView::buttonType3($main_list->getEditUrl(), $data->name) ?> %</td>
	<td><?=$form->html('visible') ?></td>
	<td><?=$main_list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
