
	<? view_command::viewLimitButton($main_list->getLimitUrl(), $main_list->getLinkPage()) ?>


<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="50px">Дата</td>
	<td width="200px">Заголовок</td>
	<td>Список адресов</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($main_list) ?>
	<td><?=$data->date ?></td>
	<td><? if($key) echo cmfAdminView::buttonType3($main_list->getEditUrl(), $data->header) ?></td>
	<td><?=$data->email ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLimitButton($main_list->getLimitUrl(), $main_list->getLinkPage()) ?>
