	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>

<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td width="100px">Заказ</td>
	<td width="150px">Статус оплаты</td>
	<td>Название</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($main_list) ?>
	<?=$main_list->getPostMove($data); ?>
	<td><?	switch($data->stop) {
				case 0:
					echo '<font color="'. $data->color .'">отменен</font>';
					break;
				case 1:
					echo '<font color="'. $data->color .'">выполняется</font>';
					break;
				case 2:
					echo '<font color="'. $data->color .'">закончен</font>';
					break;
			} ?></td>
	<td><?=$data->pay ?></td>
	<td><? if($key) echo cmfAdminView::buttonType3($main_list->getEditUrl(), $data->name) ?></td>
	<td><?=$main_list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>