<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->htmlStartForm('edit') ?>
<table class="great_table sectionEdit cmfHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
</tr>
<tr>
<td class="svet_td parentSection">Текст вверху размеров:</td>
<td class="svet_td2 parentSection"><?=$configForm->html('header', 200) ?></td>
</tr>
<tr>
<td class="svet_td parentSection">Текст внизу размеров:</td>
<td class="svet_td2 parentSection"><?=$configForm->html('footer', 300) ?></td>
</tr>
</table>
<?=$config->htmlEndForm() ?>


	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td colspan="<?=$main_list->getColspan() ?>">Название</td>
	<td width="100px">Добавить подраздел</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($main_list) ?>

	<? view_list_tree::viewTreeLine($key, $data) ?>
	<?=$main_list->getPostMove($data) ?>
	<td <?=$main_list->getColspanLine($data) ?>>
		<?=cmfAdminView::buttonType3($main_list->getEditUrl(), $data->name) ?>
	</td>

	<td><?= $data->level<1 ? cmfAdminView::buttonType3($main_list->getAddChildUrl(), 'Добавить') : '' ?> </td>
	<td><?=$form->html('visible') ?></td>
	<td><?=$main_list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
